apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: output-pipeline-run
spec:
  pipelineRef:
    name: output-pipeline
  trigger:
    type: manual
  serviceAccount: 'default'
  resources:
  - name: source-repo
    resourceRef:
      name: gh-khrm-knative-eventing-extension-example
